from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[3]
HERE=Path(__file__).resolve().parent
scores=ROOT/'research/selection/restored-test64-scores-v1/result.json'
r=json.loads(scores.read_text());selected=[x['index'] for x in r['predictions'] if x['accepted']]
assert r['fixed_threshold']==.9 and r['split']=='test' and r['attempted']==64
base='../../restoration/runs/reference625-test64-v1'
items=[{'id':i,'final':f'{base}/{i:03}/restored-1024.webp','raw':f'{base}/{i:03}/raw.png'} for i in selected]
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Priest model — latest review</title>
<style>*{box-sizing:border-box}body{margin:0;background:#080808;color:#eee;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{max-width:1500px;margin:auto;padding:32px 24px 24px}h1{font-size:24px;font-weight:500;margin:0 0 8px}p{color:#999;max-width:850px;margin:8px 0}.tag{font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:#aaa}main{max-width:1500px;margin:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:18px;padding:0 24px 40px}figure{margin:0}button{font:inherit;color:inherit;background:transparent;border:1px solid #555;border-radius:4px;padding:6px 12px;cursor:pointer}button:focus-visible{outline:2px solid #fff;outline-offset:4px}.portrait{display:block;border:0;padding:0;width:100%;border-radius:0}.portrait img{display:block;width:100%;aspect-ratio:1;object-fit:contain}figcaption{color:#888;font-size:12px;padding:6px 0}dialog{border:0;padding:0;background:#000;color:#ddd;max-width:none;max-height:none;width:100vw;height:100dvh}dialog::backdrop{background:#000}.tools{height:56px;display:flex;gap:12px;align-items:center;padding:8px 16px}.tools .spacer{flex:1}#full{display:block;width:100%;height:calc(100dvh - 56px);object-fit:contain}.note{font-size:13px;color:#bbb}@media(max-width:800px){main{grid-template-columns:repeat(2,1fr);gap:12px;padding:0 14px 28px}header{padding:24px 14px}h1{font-size:20px}}@media(max-width:500px){main{grid-template-columns:1fr}.note{display:none}}</style>
<header><div class="tag">Non-blocking review · Not deployed</div><h1>Latest priest model output</h1><p>All SELECTED portraits selected by the frozen filter from 64 new generated faces. Click a portrait for full-size review and the version before restoration.</p><p>Trained StyleGAN2 at 256px → GFPGAN restoration at 1024px. Eye detail and repeated facial resemblance still need work. These are model outputs, not training photographs.</p></header><main id="grid"></main>
<dialog id="viewer"><div class="tools"><button id="previous" aria-label="Previous portrait">←</button><span id="number"></span><button id="next" aria-label="Next portrait">→</button><button id="toggle">Before restoration</button><span class="spacer"></span><span class="note">← → to browse · Escape to close</span><button id="close">Close</button></div><img id="full" alt="Generated priest portrait"></dialog>
<script>const items=ITEMS;const grid=document.querySelector('#grid'),viewer=document.querySelector('#viewer'),full=document.querySelector('#full');let current=0,raw=false;for(const [i,item]of items.entries()){const figure=document.createElement('figure'),button=document.createElement('button'),img=document.createElement('img'),caption=document.createElement('figcaption');button.className='portrait';button.setAttribute('aria-label','Open portrait '+String(item.id).padStart(3,'0'));img.src=item.final;img.alt='Generated priest '+item.id;caption.textContent='#'+String(item.id).padStart(3,'0');button.append(img);button.onclick=()=>{current=i;raw=false;render();viewer.showModal()};figure.append(button,caption);grid.append(figure)}function render(){const item=items[current];full.src=raw?item.raw:item.final;document.querySelector('#number').textContent='#'+String(item.id).padStart(3,'0');document.querySelector('#toggle').textContent=raw?'Show restored':'Before restoration'}function step(n){current=(current+n+items.length)%items.length;raw=false;render()}document.querySelector('#previous').onclick=()=>step(-1);document.querySelector('#next').onclick=()=>step(1);document.querySelector('#toggle').onclick=()=>{raw=!raw;render()};document.querySelector('#close').onclick=()=>viewer.close();document.addEventListener('keydown',e=>{if(!viewer.open)return;if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1)});</script></html>'''.replace('SELECTED',str(len(items))).replace('ITEMS',json.dumps(items))
(HERE/'index.html').write_text(html)
(HERE/'manifest.json').write_text(json.dumps({'source':str(scores.relative_to(ROOT)),'source_sha256':hashlib.sha256(scores.read_bytes()).hexdigest(),'selected_indices':selected,'all_filter_accepts_included':True,'no_further_hand_selection':True,'attempted':64,'threshold':.9,'production_approved':False},indent=2)+'\n')
print({'selected':selected,'preview':str(HERE/'index.html')})
